(() => {
  const root = document.getElementById('operationsMap'), rank = document.getElementById('storeRank');
  const esc = v => String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num = v => Number(String(v || '').replace(/[^\d.\-]/g, '')) || 0;
  const rows = () => [...rank.querySelectorAll('tbody tr')].map(tr => { const c=[...tr.children].map(x=>x.textContent.trim()); return {store:c[0],type:c[1],sku:c[3],external:num(c[6]),suggested:num(c[9]),high:num(c[10]),extreme:num(c[11])}; }).filter(x=>x.store);
  const state = r => r.extreme || r.suggested / 754 >= .8 ? 'high' : r.high || r.suggested / 754 >= .5 ? 'medium' : 'low';
  const names = {high:'高压',medium:'中压',low:'低压'};
  const choose = store => { const select=document.getElementById('storeSelect'); if(select && [...select.options].some(x=>x.value===store)){select.value=store;select.dispatchEvent(new Event('change',{bubbles:true}));} const selection=root.querySelector('#mapSelected'); selection.innerHTML=`<div><span class="eyebrow">当前选择</span><h3>${esc(store)}</h3><p>已切换当前门店；进入门店执行可查看商品级补货、风险与陈列详情。</p></div><button type="button" id="goStore">查看补货方案</button>`; root.querySelector('#goStore').onclick=()=>document.querySelector('[data-view="store"]')?.click(); root.querySelectorAll('[data-store]').forEach(x=>x.classList.toggle('selected',x.dataset.store===store)); };
  const render = () => { const data=rows(); if(!data.length || root.dataset.busy==='1') return; root.dataset.busy='1'; const urgent=data.filter(r=>state(r)!=='low').sort((a,b)=>b.suggested-a.suggested).slice(0,5); const tile=r=>{const s=state(r),p=Math.min(100,Math.round(r.suggested/754*100));return `<button class="map-store ${s}" data-store="${esc(r.store)}"><span class="map-store-head"><i></i>${esc(r.store)}</span><span class="map-state">${names[s]}</span><strong>${p}%</strong><span class="map-caption">外储压力</span><b>${r.external} 箱待补</b><small>已纳入 ${r.sku||0} SKU</small></button>`}; const rail=r=>`<button class="rail-store ${state(r)}" data-store="${esc(r.store)}"><i></i><span>${esc(r.store)}<small>${esc(r.type||'门店')}</small></span><b>${r.external} 箱</b></button>`; const priority=(r,i)=>`<button class="priority-row" data-store="${esc(r.store)}"><em>${i+1}</em><span><b>${esc(r.store)}</b><small>${names[state(r)]} · 建议外储 ${r.suggested}L</small></span><strong>${r.external} 箱</strong></button>`;
    root.innerHTML=`<section class="map-heading"><div><span class="eyebrow">经营地图</span><h2>一眼识别需要优先处理的门店</h2><p>按建议外储占 754L 上限自动分级，点击门店进入执行明细。</p></div><div class="map-toolbar"><label class="map-search"><span>搜索</span><input id="mapSearch" type="search" placeholder="搜索门店"></label><button id="mapListToggle" type="button">查看列表</button></div></section><div class="map-layout"><aside class="map-rail"><div class="map-rail-title"><strong>门店列表</strong><span>${data.length} 家</span></div><div class="map-rail-list">${data.slice(0,9).map(rail).join('')}</div></aside><section class="map-canvas"><div class="map-canvas-title">门店经营分布 <span>红色优先补货 · 橙色关注容量 · 绿色库存充足</span></div><div class="map-grid">${data.slice(0,12).map(tile).join('')}</div></section><aside class="priority-panel"><div class="priority-head"><div><span class="eyebrow">优先处理</span><h3>建议补货</h3></div><span>${urgent.length} 项</span></div>${urgent.length?urgent.map(priority).join(''):'<div class="map-empty">当前门店均处于安全范围</div>'}</aside></div><div class="map-selected" id="mapSelected"><div><span class="eyebrow">当前选择</span><h3>选择一个门店查看补货方案</h3><p>系统会保留现有测算规则，跳转后可查看商品、风险和陈列详情。</p></div><button type="button" disabled>查看补货方案</button></div>`;
    root.dataset.busy='0'; root.querySelectorAll('[data-store]').forEach(x=>x.onclick=()=>choose(x.dataset.store)); root.querySelector('#mapSearch').oninput=e=>root.querySelectorAll('.map-store,.rail-store').forEach(x=>x.hidden=e.target.value && !x.dataset.store.includes(e.target.value.trim())); root.querySelector('#mapListToggle').onclick=()=>document.querySelector('.map-rail')?.scrollIntoView({behavior:'smooth',block:'nearest'});
  };
  new MutationObserver(()=>requestAnimationFrame(render)).observe(rank,{childList:true,subtree:true}); render();
})();